# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180711_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
