# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20180711_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddits',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
