# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20180711_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddits',
            old_name='subreddits',
            new_name='subreddit_text',
        ),
    ]
