# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-14 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20180711_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddits',
            old_name='subreddit_text',
            new_name='subreddit_name',
        ),
    ]
